name: NeyroCore
version: '1.0.0'
main: com.github.otsns.neyroCore.NeyroCore
api-version: '1.21'
softdepend: [ProtocolLib]
authors: [ otsns ]
description: Server core plugin
commands:
  core: # Добавьте эту секцию
    description: Reload plugin configuration
    default: op
    usage: /core reload
    permission: neyrocore.reload
    permission-message: You don't have permission to reload the plugin
