name: NeyroCore
version: '1.0.0'
main: com.github.otsns.neyroCore.NeyroCore
api-version: '1.21'
authors: [ otsns ]
description: Server core plugin
commands:
  neyrocore:
    description: "Reload the NeyroCore configuration."
    usage: /core reload
permissions:
  neyrocore.reload:
    description: "Allows reload the Core configuration."
    default: op
