name: NeyroCore
version: 1.0.0
main: com.github.otsns.neyroCore.NeyroCore
api-version: 1.21
softdepend: [ProtocolLib]

commands:
  core:
    description: Reload plugin configuration
    usage: /core reload
    permission: neyrocore.reload
    permission-message: "&cYou don't have permission!"

permissions:
  neyrocore.reload:
    description: Allows reloading plugin configuration
    default: op
